name: push dag docker image to ECR 
on: 
  push:
    branches:
      - 'main'
    paths:
      - 'docker_assignment/catsdogs-cloud9-master/catsdogs-cloud9-master/dogs/'
      

 jobs: 
   running_shell_command:
     runs-on: ubuntu-latest
     steps: 
       - name: cloning git repo  
         uses: actions/checkout@v2
      
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ap-south-1

       - name: Login to Amazon ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v1

       - name: Build, tag, and push image to Amazon ECR
         env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
           ECR_REPOSITORY: dog_image
           IMAGE_TAG: latest
         run: |
           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG dog_image/.
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
